### ISSUE TITLE
No way to see difference between internal server error and invalid input error

### ISSUE THREAD

**Issue by barbushin** [dnegometyanov/cordial-auth#2]
https://github.com/dnegometyanov/cordial-auth/blob/9ecd59edfbb3597e1d1261c3d9e829d52a5eae40/app/Services/AuthService.php#L59-L61

https://github.com/dnegometyanov/cordial-auth/blob/9ecd59edfbb3597e1d1261c3d9e829d52a5eae40/app/Services/AuthService.php#L87-L93

There must be specific exception class for this type of error

**Comment by dnegometyanov** [comment]
Agree, thought on that, but did not implemented it to save time :(

Btw about this test task in general: It has several very similar methods like acrivate and reset / change.
For future assignments I would recommend to remove some of them, because significant time was spent on doing almost the same functionality on several places, while it might be spent on real code quality improvements. 
I general it took whole working day like 6 hours that I've spent in 2 evenings on Sunday and Monday and was pretty bored to repeat almost the same in several places :(

**Comment by barbushin** [comment]
Thanks for advice!

**Comment by dnegometyanov** [comment]
Have resolved issue in recent commits.
