### ISSUE TITLE
Reset code is detected as expired when it's not expired

### ISSUE THREAD

**Issue by barbushin** [dnegometyanov/cordial-auth#6]
https://github.com/dnegometyanov/cordial-auth/blob/9ecd59edfbb3597e1d1261c3d9e829d52a5eae40/app/Services/AuthService.php#L150-L152

**Comment by dnegometyanov** [comment]
This test passed on my env https://github.com/dnegometyanov/cordial-auth/blob/92effc5798e06f9e4b305b4b8209e60ea06168e0/tests/Unit/AuthServiceTest.php#L224
Also manual testing was ok.

I've expirienced some problems with datetime in the DB and fixed them with DB_TIMEZONE=+03:00 in .env - that may be the cause.

**Comment by barbushin** [comment]
But logic of how it works is incorrect, no?

**Comment by dnegometyanov** [comment]
Hmms, in general logic is `if current date is greater than expiration date, then it's expired.`, can't get why it's incorrect.
Maybe I should better use Carbon methods for comparison like `->gt()` instead of `>` ....
It has 2 tests on success and expired cases, and they pass...
So probably I give up on what you mean as incorrect logic :(

In general thanks for good review !

**Comment by barbushin** [comment]
Oh, sorry, you're right. I misunderstood field title. Thanks for explaining!
